# pyright: reportMissingImports=false, reportMissingModuleSource=false
import os
import shutil
from pathlib import Path
from typing import Callable

import numpy as np

from solver import solve_poisson as _default_solver, u_exact_np as _default_u_exact
from mesh_helpers import (
    write_cube_mesh,
    generate_initial_mesh,
    read_medit_to_dolfinx,
    to_vtu,
    build_dolfinx_to_medit_map,
    build_metric,
    adapt_mesh_mmg,
    save_computed_quantities,
)
from eta_estimator import (
    compute_jacobian_svd,
    adapt_h,
    compute_anisotropic_eta,
    compute_G_tilde,
    compute_G_P,
    compute_lambda_P,
    compute_sigma_P,
    compute_gradient_dg0,
)
from error_metrics import compute_error_metrics, compute_error_metrics_ZZ, compute_error_norms


def run_adaptive_poisson(
    results_dir: Path | str,
    solver: Callable | None = None,
    u_numpy: Callable[[np.ndarray], np.ndarray] | None = None,
    n_loop: int = 5,
    hmax: float = 1.0,
    hmin: float = 1e-10,
    hgrad: float = -1,
    tol: float = 0.5,
    alpha: float = 0.25,
    correction_factor: float = 1.5,
    degree_raise: int = 3,
    mmg3d_exe: str = "/usr/local/bin/mmg3d_O3",
    initial_mesh_file: Path | str | None = None,
) -> tuple:
    """Run the anisotropic adaptive Poisson algorithm (Table 1.6).

    Parameters
    ----------
    results_dir :
        Root output directory.  Sub-directories will be created automatically:
        ``meshes/``, ``sols/``, ``vtk/``, ``compute_errs/``.
    solver :
        Callable ``solver(msh) -> (u_h, f_rhs)``.  Defaults to
        :func:`solver.solve_poisson` (tanh boundary-layer problem).
    u_numpy :
        Exact solution callback ``u_numpy(x)`` used for error metrics.
        Defaults to :func:`solver.u_exact_np`.
    n_loop :
        Number of adaptive iterations.
    hmax, hmin :
        Upper / lower bounds for mesh size passed to MMG3D.
    hgrad :
        Mesh-size gradation factor for MMG3D (``-1`` disables it).
    tol :
        Equidistribution tolerance.
    alpha :
        Half-width of the equidistribution acceptance band.
    correction_factor :
        Multiplier applied when coarsening or refining ``h_p``.
    degree_raise :
        Degree increment used in error-norm projection space.
    mmg3d_exe :
        Path to the MMG3D executable.
    initial_mesh_file :
        Path to an existing Medit ``.mesh`` file to use as the starting mesh
        instead of generating one from scratch.  When ``None`` (default) the
        initial mesh is generated by MMG3D from a coarse cube.

    Returns
    -------
    msh :
        Final mesh (DOLFINx).
    u_h :
        Final FEM solution.
    h_p :
        Final target mesh-size array, shape ``(n_vertices, tdim)``.
    final_metrics :
        Dictionary with final-iteration metrics and estimators.
    iteration_metrics :
        List of per-iteration dicts with keys ``loop_idx``, ``n_vertices``,
        and ``TRE``.
    """
    if solver is None:
        solver = _default_solver
    if u_numpy is None:
        u_numpy = _default_u_exact

    results_dir = Path(results_dir)
    meshes_dir       = results_dir / "meshes"
    sols_dir         = results_dir / "sols"
    vtk_dir          = results_dir / "vtk"
    compute_errs_dir = results_dir / "compute_errs"

    for d in (results_dir, meshes_dir, sols_dir, vtk_dir, compute_errs_dir):
        d.mkdir(exist_ok=True, parents=True)

    mmg_log_file = results_dir / "mmg_output.txt"

    print(f"[INIT] Results directory: {results_dir}")
    print(f"       meshes → {meshes_dir}")
    print(f"       sols   → {sols_dir}")
    print(f"       vtk    → {vtk_dir}")
    print(f"       errs   → {compute_errs_dir}")

    # ------------------------------------------------------------------
    # STEP 1: Generate initial mesh or copy provided one
    # ------------------------------------------------------------------
    mesh_0_path = str(meshes_dir / "mesh_0.mesh")

    if initial_mesh_file is None:
        print("\n[STEP 1] Generating initial mesh...")
        coarse_mesh_path = str(meshes_dir / "mesh_coarse.mesh")
        write_cube_mesh(coarse_mesh_path)
        if not os.path.isfile(coarse_mesh_path):
            raise FileNotFoundError(f"Coarse mesh not created: {coarse_mesh_path}")
        generate_initial_mesh(coarse_mesh_path, mesh_0_path, mmg3d_exe, hmax=hmax, hgrad=-1)
        if not os.path.isfile(mesh_0_path):
            raise FileNotFoundError(f"Initial mesh not created by MMG: {mesh_0_path}")
    else:
        print(f"\n[STEP 1] Using provided initial mesh: {initial_mesh_file}")
        shutil.copy2(str(initial_mesh_file), mesh_0_path)

    msh = read_medit_to_dolfinx(mesh_0_path)
    print(
        f"  Initial mesh: "
        f"{msh.topology.index_map(3).size_global} cells, "
        f"{msh.topology.index_map(0).size_global} vertices"
    )

    vtu_path = to_vtu(mesh_0_path, output_dir=vtk_dir)
    if vtu_path:
        print(f"  VTU saved: {Path(vtu_path).name}")

    # ------------------------------------------------------------------
    # MAIN ADAPTIVE LOOP
    # ------------------------------------------------------------------
    u_h = None
    h_p = None
    final_metrics = {}
    iteration_metrics = []

    for loop_idx in range(n_loop):
        print(f"\n{'='*70}")
        print(f"LOOP {loop_idx + 1}/{n_loop}")
        print(f"{'='*70}")

        # ---- Step 2: Solve ----------------------------------------
        print("\n[2] Solving Poisson equation...")
        u_h, f_rhs = solver(msh)
        tdim = msh.topology.dim
        n_vertices_iter = int(msh.topology.index_map(0).size_global)
        print(
            f"  Solution on "
            f"{msh.topology.index_map(tdim).size_global} cells, "
            f"{n_vertices_iter} vertices"
        )

        # ---- Per-iteration TRE & u_h numpy checkpoint -------------
        print("\n[2b] Computing TRE and saving u_h checkpoint...")
        norm_grad_e, norm_grad_u, norm_grad_uh = compute_error_norms(
            u_h, u_numpy, degree_raise
        )
        tre_iter = float(norm_grad_e / norm_grad_u)
        iteration_metrics.append(
            {"loop_idx": loop_idx, "n_vertices": n_vertices_iter, "TRE": tre_iter}
        )
        np.save(str(compute_errs_dir / f"uh_loop_{loop_idx:02d}.npy"), u_h.x.array)
        print(
            f"  TRE={tre_iter:.6e}  n_vertices={n_vertices_iter}"
            f"  → uh_loop_{loop_idx:02d}.npy"
        )

        # ---- Step 3: Cell-wise quantities -------------------------
        print("\n[3] Computing cell-wise quantities...")
        svd = compute_jacobian_svd(msh)
        eta_k, res1, omegas = compute_anisotropic_eta(u_h, f_rhs)
        eta_k_i = np.asarray(res1)[None, :] * np.asarray(omegas)
        print(f"  eta_k_i shape: {eta_k_i.shape}  (directions × cells)")

        # compute_G_tilde now also returns the ZZ error as a fem.Function
        G, eta_zz_fn = compute_G_tilde(u_h)
        print("  G_tilde + eta_zz computed")

        # ---- Step 4: Vertex-wise quantities -----------------------
        print("\n[4] Computing vertex-wise quantities...")
        G_P_arr, Q = compute_G_P(u_h, G)
        sigma_p   = compute_sigma_P(u_h, eta_k_i)
        lambda_p  = compute_lambda_P(u_h, svd)
        print(f"  G_P: {G_P_arr.shape},  Q: {Q.shape},  lambda_P: {lambda_p.shape}")

        # ---- Step 5: Equidistribution check & h update ------------
        print("\n[5] Checking equidistribution...")
        h_p = adapt_h(msh, eta_k_i, u_h, tol, lambda_p, alpha, correction_factor, sigma_p)
        h_p = np.clip(h_p, hmin, hmax)

        # ---- Step 6: Build metric tensor --------------------------
        print("\n[6] Building metric tensor...")
        mesh_path = str(meshes_dir / f"mesh_{loop_idx}.mesh")
        sol_path  = str(sols_dir   / f"mesh_{loop_idx}.sol")
        perm = build_dolfinx_to_medit_map(msh)
        build_metric(h_p, Q, perm, mesh_path, sol_path)
        print(f"  Metric → {Path(sol_path).name}")

        export_solution = True
        vtu_path = to_vtu(
            mesh_path,
            output_dir=vtk_dir,
            write_solution=export_solution,
            u_h=u_h,
            dof_to_medit=perm,
        )
        if vtu_path and export_solution:
            print(f"  VTU (+u_h) saved: {Path(vtu_path).name}")
        elif vtu_path:
            print(f"  VTU (mesh only) saved: {Path(vtu_path).name}")

        # ---- Step 7: MMG adaptation (skip on last iteration) ------
        if loop_idx < n_loop - 1:
            print("\n[7] Running MMG3D...")
            next_mesh_path = str(meshes_dir / f"mesh_{loop_idx + 1}.mesh")
            adapt_mesh_mmg(
                mesh_path, next_mesh_path, sol_path,
                mmg_log_file, mmg3d_exe,
                hgrad, hmin, hmax,
                vtk_dir=vtk_dir,
            )
            msh = read_medit_to_dolfinx(next_mesh_path)
            print(
                f"  New mesh: "
                f"{msh.topology.index_map(tdim).size_global} cells, "
                f"{msh.topology.index_map(0).size_global} vertices"
            )

        # ---- Last iteration: full checkpoint + final metrics ------
        if loop_idx == n_loop - 1:
            print("\n[SAVE] Storing computed quantities (adios4dolfinx)...")
            grad_uh = compute_gradient_dg0(u_h)
            save_computed_quantities(
                compute_errs_dir, u_h, grad_uh, eta_k, eta_zz_fn,
                time=float(loop_idx),
            )

            # Reuse norms computed in the per-iteration block above
            eta_aniso = float(np.sqrt(np.sum(np.asarray(eta_k))))
            gdim = msh.geometry.dim
            eta_zz_val = float(
                np.sqrt(max(sum(np.sum(G[(i, i)]) for i in range(gdim)), 0.0))
            )

            final_metrics = {
                "n_vertices": n_vertices_iter,
                "TRE": tre_iter,
                "ERE_anisotropic": float(eta_aniso / norm_grad_uh),
                "EI_anisotropic": float(eta_aniso / norm_grad_e),
                "ERE_ZZ": float(eta_zz_val / norm_grad_uh),
                "EI_ZZ": float(eta_zz_val / norm_grad_e),
                "eta_anisotropic": eta_aniso,
                "eta_ZZ": eta_zz_val,
            }

            metrics_path = compute_errs_dir / "final_error_metrics.npz"
            np.savez(metrics_path, **final_metrics)
            print("  Final metrics:")
            print(
                f"    n_vertices={n_vertices_iter}  TRE={tre_iter:.6e}"
                f"  ERE_aniso={final_metrics['ERE_anisotropic']:.6e}"
                f"  EI_aniso={final_metrics['EI_anisotropic']:.6e}"
            )
            print(
                f"    ERE_ZZ={final_metrics['ERE_ZZ']:.6e}"
                f"  EI_ZZ={final_metrics['EI_ZZ']:.6e}"
                f"  eta_aniso={eta_aniso:.6e}  eta_ZZ={eta_zz_val:.6e}"
            )
            print(f"  Saved metrics → {metrics_path}")

        print(f"\n[END] Iteration {loop_idx + 1} complete")

    print(f"\n{'='*70}")
    print("ADAPTIVE LOOP COMPLETE")
    print(f"{'='*70}")
    print(f"  Meshes      → {meshes_dir}")
    print(f"  Sol files   → {sols_dir}")
    print(f"  VTK files   → {vtk_dir}")
    print(f"  Quantities  → {compute_errs_dir}")
    print(f"  MMG log     → {mmg_log_file}")

    return msh, u_h, h_p, final_metrics, iteration_metrics
